---
- name: Installing Zabbix Agent ...
  yum: name=zabbix-agent state=installed

- name: Configuring Zabbix Agent ...
  template: src=zabbix_agent.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode=0644

- name: Starting zabbix agent
  service: name=zabbix-agent state=restarted
